// Code generated by "genhandler ItemRequest"; DO NOT EDIT

package sdp

import (
	"context"

	"github.com/nats-io/nats.go"
	"go.opentelemetry.io/otel/trace"
)

func NewItemRequestHandler(spanName string, h func(ctx context.Context, i *ItemRequest), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i ItemRequest
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, &i)
		},
		tracer,
	)
}

func NewRawItemRequestHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *ItemRequest), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i ItemRequest
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, m, &i)
		},
		tracer,
	)
}

func NewAsyncRawItemRequestHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *ItemRequest), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewAsyncOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i ItemRequest
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, m, &i)
		},
		tracer,
	)
}
