// Code generated by "genhandler Response"; DO NOT EDIT

package sdp

import (
	"context"

	"github.com/nats-io/nats.go"
	"go.opentelemetry.io/otel/trace"
)

func NewResponseHandler(spanName string, h func(ctx context.Context, i *Response), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i Response
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, &i)
		},
		tracer,
	)
}

func NewRawResponseHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *Response), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i Response
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, m, &i)
		},
		tracer,
	)
}
