// Code generated by "genhandler QueryError"; DO NOT EDIT

package sdp

import (
	"context"

	"github.com/nats-io/nats.go"
	"go.opentelemetry.io/otel/trace"
)

func NewQueryErrorHandler(spanName string, h func(ctx context.Context, i *QueryError), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i QueryError
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, &i)
		},
		tracer,
	)
}

func NewRawQueryErrorHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *QueryError), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i QueryError
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, m, &i)
		},
		tracer,
	)
}

func NewAsyncRawQueryErrorHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *QueryError), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewAsyncOtelExtractingHandler(
		spanName,
		func(ctx context.Context, m *nats.Msg) {
			var i QueryError
			err := Unmarshal(ctx, m.Data, &i)
			if err != nil {
				return
			}
			h(ctx, m, &i)
		},
		tracer,
	)
}
