// Code generated by "genhandler Item"; DO NOT EDIT

package sdp

import (
	"context"

	"github.com/nats-io/nats.go"
	"go.opentelemetry.io/otel/trace"
)

func NewItemHandler(spanName string, h func(ctx context.Context, i *Item), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(spanName, func(ctx context.Context, m *nats.Msg) {
		var i Item
		err := Unmarshal(ctx, m.Data, &i)
		if err != nil {
			return
		}
		h(ctx, &i)
	})
}

func NewRawItemHandler(spanName string, h func(ctx context.Context, m *nats.Msg, i *Item), spanOpts ...trace.SpanStartOption) nats.MsgHandler {
	return NewOtelExtractingHandler(spanName, func(ctx context.Context, m *nats.Msg) {
		var i Item
		err := Unmarshal(ctx, m.Data, &i)
		if err != nil {
			return
		}
		h(ctx, m, &i)
	})
}
