// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: account.proto

package sdpconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	sdp_go "github.com/overmindtech/sdp-go"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "account.AdminService"
	// ManagementServiceName is the fully-qualified name of the ManagementService service.
	ManagementServiceName = "account.ManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceListAccountsProcedure is the fully-qualified name of the AdminService's ListAccounts
	// RPC.
	AdminServiceListAccountsProcedure = "/account.AdminService/ListAccounts"
	// AdminServiceCreateAccountProcedure is the fully-qualified name of the AdminService's
	// CreateAccount RPC.
	AdminServiceCreateAccountProcedure = "/account.AdminService/CreateAccount"
	// AdminServiceGetAccountProcedure is the fully-qualified name of the AdminService's GetAccount RPC.
	AdminServiceGetAccountProcedure = "/account.AdminService/GetAccount"
	// AdminServiceDeleteAccountProcedure is the fully-qualified name of the AdminService's
	// DeleteAccount RPC.
	AdminServiceDeleteAccountProcedure = "/account.AdminService/DeleteAccount"
	// AdminServiceListSourcesProcedure is the fully-qualified name of the AdminService's ListSources
	// RPC.
	AdminServiceListSourcesProcedure = "/account.AdminService/ListSources"
	// AdminServiceCreateSourceProcedure is the fully-qualified name of the AdminService's CreateSource
	// RPC.
	AdminServiceCreateSourceProcedure = "/account.AdminService/CreateSource"
	// AdminServiceGetSourceProcedure is the fully-qualified name of the AdminService's GetSource RPC.
	AdminServiceGetSourceProcedure = "/account.AdminService/GetSource"
	// AdminServiceUpdateSourceProcedure is the fully-qualified name of the AdminService's UpdateSource
	// RPC.
	AdminServiceUpdateSourceProcedure = "/account.AdminService/UpdateSource"
	// AdminServiceDeleteSourceProcedure is the fully-qualified name of the AdminService's DeleteSource
	// RPC.
	AdminServiceDeleteSourceProcedure = "/account.AdminService/DeleteSource"
	// AdminServiceKeepaliveSourcesProcedure is the fully-qualified name of the AdminService's
	// KeepaliveSources RPC.
	AdminServiceKeepaliveSourcesProcedure = "/account.AdminService/KeepaliveSources"
	// AdminServiceCreateTokenProcedure is the fully-qualified name of the AdminService's CreateToken
	// RPC.
	AdminServiceCreateTokenProcedure = "/account.AdminService/CreateToken"
	// ManagementServiceGetAccountProcedure is the fully-qualified name of the ManagementService's
	// GetAccount RPC.
	ManagementServiceGetAccountProcedure = "/account.ManagementService/GetAccount"
	// ManagementServiceListSourcesProcedure is the fully-qualified name of the ManagementService's
	// ListSources RPC.
	ManagementServiceListSourcesProcedure = "/account.ManagementService/ListSources"
	// ManagementServiceCreateSourceProcedure is the fully-qualified name of the ManagementService's
	// CreateSource RPC.
	ManagementServiceCreateSourceProcedure = "/account.ManagementService/CreateSource"
	// ManagementServiceGetSourceProcedure is the fully-qualified name of the ManagementService's
	// GetSource RPC.
	ManagementServiceGetSourceProcedure = "/account.ManagementService/GetSource"
	// ManagementServiceUpdateSourceProcedure is the fully-qualified name of the ManagementService's
	// UpdateSource RPC.
	ManagementServiceUpdateSourceProcedure = "/account.ManagementService/UpdateSource"
	// ManagementServiceDeleteSourceProcedure is the fully-qualified name of the ManagementService's
	// DeleteSource RPC.
	ManagementServiceDeleteSourceProcedure = "/account.ManagementService/DeleteSource"
	// ManagementServiceKeepaliveSourcesProcedure is the fully-qualified name of the ManagementService's
	// KeepaliveSources RPC.
	ManagementServiceKeepaliveSourcesProcedure = "/account.ManagementService/KeepaliveSources"
	// ManagementServiceCreateTokenProcedure is the fully-qualified name of the ManagementService's
	// CreateToken RPC.
	ManagementServiceCreateTokenProcedure = "/account.ManagementService/CreateToken"
)

// AdminServiceClient is a client for the account.AdminService service.
type AdminServiceClient interface {
	// Lists the details of all NATS Accounts
	ListAccounts(context.Context, *connect_go.Request[sdp_go.ListAccountsRequest]) (*connect_go.Response[sdp_go.ListAccountsResponse], error)
	// Creates a new account, public_nkey will be autogenerated
	CreateAccount(context.Context, *connect_go.Request[sdp_go.CreateAccountRequest]) (*connect_go.Response[sdp_go.CreateAccountResponse], error)
	// Get the details of a given account
	GetAccount(context.Context, *connect_go.Request[sdp_go.AdminGetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error)
	// Deletes an account
	DeleteAccount(context.Context, *connect_go.Request[sdp_go.DeleteAccountRequest]) (*connect_go.Response[sdp_go.DeleteAccountResponse], error)
	// Lists all sources within the closen account
	ListSources(context.Context, *connect_go.Request[sdp_go.AdminListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error)
	// Creates a new source within the closen account
	CreateSource(context.Context, *connect_go.Request[sdp_go.AdminCreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error)
	// Get the details of a source within the closen account
	GetSource(context.Context, *connect_go.Request[sdp_go.AdminGetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error)
	// Update the details of a source within the closen account
	UpdateSource(context.Context, *connect_go.Request[sdp_go.AdminUpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error)
	// Deletes a source from a closen account
	DeleteSource(context.Context, *connect_go.Request[sdp_go.AdminDeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error)
	// Updates sources to keep them running in the background. This can be used
	// to add explicit action, when the built-in keepalives are not sufficient.
	KeepaliveSources(context.Context, *connect_go.Request[sdp_go.AdminKeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error)
	// Create a new NATS token for a given public NKey. The user requesting must
	// control the associated private key also in order to connect to NATS as
	// the token is not enough on its own
	CreateToken(context.Context, *connect_go.Request[sdp_go.AdminCreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error)
}

// NewAdminServiceClient constructs a client for the account.AdminService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &adminServiceClient{
		listAccounts: connect_go.NewClient[sdp_go.ListAccountsRequest, sdp_go.ListAccountsResponse](
			httpClient,
			baseURL+AdminServiceListAccountsProcedure,
			opts...,
		),
		createAccount: connect_go.NewClient[sdp_go.CreateAccountRequest, sdp_go.CreateAccountResponse](
			httpClient,
			baseURL+AdminServiceCreateAccountProcedure,
			opts...,
		),
		getAccount: connect_go.NewClient[sdp_go.AdminGetAccountRequest, sdp_go.GetAccountResponse](
			httpClient,
			baseURL+AdminServiceGetAccountProcedure,
			opts...,
		),
		deleteAccount: connect_go.NewClient[sdp_go.DeleteAccountRequest, sdp_go.DeleteAccountResponse](
			httpClient,
			baseURL+AdminServiceDeleteAccountProcedure,
			opts...,
		),
		listSources: connect_go.NewClient[sdp_go.AdminListSourcesRequest, sdp_go.ListSourcesResponse](
			httpClient,
			baseURL+AdminServiceListSourcesProcedure,
			opts...,
		),
		createSource: connect_go.NewClient[sdp_go.AdminCreateSourceRequest, sdp_go.CreateSourceResponse](
			httpClient,
			baseURL+AdminServiceCreateSourceProcedure,
			opts...,
		),
		getSource: connect_go.NewClient[sdp_go.AdminGetSourceRequest, sdp_go.GetSourceResponse](
			httpClient,
			baseURL+AdminServiceGetSourceProcedure,
			opts...,
		),
		updateSource: connect_go.NewClient[sdp_go.AdminUpdateSourceRequest, sdp_go.UpdateSourceResponse](
			httpClient,
			baseURL+AdminServiceUpdateSourceProcedure,
			opts...,
		),
		deleteSource: connect_go.NewClient[sdp_go.AdminDeleteSourceRequest, sdp_go.DeleteSourceResponse](
			httpClient,
			baseURL+AdminServiceDeleteSourceProcedure,
			opts...,
		),
		keepaliveSources: connect_go.NewClient[sdp_go.AdminKeepaliveSourcesRequest, sdp_go.KeepaliveSourcesResponse](
			httpClient,
			baseURL+AdminServiceKeepaliveSourcesProcedure,
			opts...,
		),
		createToken: connect_go.NewClient[sdp_go.AdminCreateTokenRequest, sdp_go.CreateTokenResponse](
			httpClient,
			baseURL+AdminServiceCreateTokenProcedure,
			opts...,
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	listAccounts     *connect_go.Client[sdp_go.ListAccountsRequest, sdp_go.ListAccountsResponse]
	createAccount    *connect_go.Client[sdp_go.CreateAccountRequest, sdp_go.CreateAccountResponse]
	getAccount       *connect_go.Client[sdp_go.AdminGetAccountRequest, sdp_go.GetAccountResponse]
	deleteAccount    *connect_go.Client[sdp_go.DeleteAccountRequest, sdp_go.DeleteAccountResponse]
	listSources      *connect_go.Client[sdp_go.AdminListSourcesRequest, sdp_go.ListSourcesResponse]
	createSource     *connect_go.Client[sdp_go.AdminCreateSourceRequest, sdp_go.CreateSourceResponse]
	getSource        *connect_go.Client[sdp_go.AdminGetSourceRequest, sdp_go.GetSourceResponse]
	updateSource     *connect_go.Client[sdp_go.AdminUpdateSourceRequest, sdp_go.UpdateSourceResponse]
	deleteSource     *connect_go.Client[sdp_go.AdminDeleteSourceRequest, sdp_go.DeleteSourceResponse]
	keepaliveSources *connect_go.Client[sdp_go.AdminKeepaliveSourcesRequest, sdp_go.KeepaliveSourcesResponse]
	createToken      *connect_go.Client[sdp_go.AdminCreateTokenRequest, sdp_go.CreateTokenResponse]
}

// ListAccounts calls account.AdminService.ListAccounts.
func (c *adminServiceClient) ListAccounts(ctx context.Context, req *connect_go.Request[sdp_go.ListAccountsRequest]) (*connect_go.Response[sdp_go.ListAccountsResponse], error) {
	return c.listAccounts.CallUnary(ctx, req)
}

// CreateAccount calls account.AdminService.CreateAccount.
func (c *adminServiceClient) CreateAccount(ctx context.Context, req *connect_go.Request[sdp_go.CreateAccountRequest]) (*connect_go.Response[sdp_go.CreateAccountResponse], error) {
	return c.createAccount.CallUnary(ctx, req)
}

// GetAccount calls account.AdminService.GetAccount.
func (c *adminServiceClient) GetAccount(ctx context.Context, req *connect_go.Request[sdp_go.AdminGetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// DeleteAccount calls account.AdminService.DeleteAccount.
func (c *adminServiceClient) DeleteAccount(ctx context.Context, req *connect_go.Request[sdp_go.DeleteAccountRequest]) (*connect_go.Response[sdp_go.DeleteAccountResponse], error) {
	return c.deleteAccount.CallUnary(ctx, req)
}

// ListSources calls account.AdminService.ListSources.
func (c *adminServiceClient) ListSources(ctx context.Context, req *connect_go.Request[sdp_go.AdminListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error) {
	return c.listSources.CallUnary(ctx, req)
}

// CreateSource calls account.AdminService.CreateSource.
func (c *adminServiceClient) CreateSource(ctx context.Context, req *connect_go.Request[sdp_go.AdminCreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error) {
	return c.createSource.CallUnary(ctx, req)
}

// GetSource calls account.AdminService.GetSource.
func (c *adminServiceClient) GetSource(ctx context.Context, req *connect_go.Request[sdp_go.AdminGetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error) {
	return c.getSource.CallUnary(ctx, req)
}

// UpdateSource calls account.AdminService.UpdateSource.
func (c *adminServiceClient) UpdateSource(ctx context.Context, req *connect_go.Request[sdp_go.AdminUpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error) {
	return c.updateSource.CallUnary(ctx, req)
}

// DeleteSource calls account.AdminService.DeleteSource.
func (c *adminServiceClient) DeleteSource(ctx context.Context, req *connect_go.Request[sdp_go.AdminDeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error) {
	return c.deleteSource.CallUnary(ctx, req)
}

// KeepaliveSources calls account.AdminService.KeepaliveSources.
func (c *adminServiceClient) KeepaliveSources(ctx context.Context, req *connect_go.Request[sdp_go.AdminKeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error) {
	return c.keepaliveSources.CallUnary(ctx, req)
}

// CreateToken calls account.AdminService.CreateToken.
func (c *adminServiceClient) CreateToken(ctx context.Context, req *connect_go.Request[sdp_go.AdminCreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error) {
	return c.createToken.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the account.AdminService service.
type AdminServiceHandler interface {
	// Lists the details of all NATS Accounts
	ListAccounts(context.Context, *connect_go.Request[sdp_go.ListAccountsRequest]) (*connect_go.Response[sdp_go.ListAccountsResponse], error)
	// Creates a new account, public_nkey will be autogenerated
	CreateAccount(context.Context, *connect_go.Request[sdp_go.CreateAccountRequest]) (*connect_go.Response[sdp_go.CreateAccountResponse], error)
	// Get the details of a given account
	GetAccount(context.Context, *connect_go.Request[sdp_go.AdminGetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error)
	// Deletes an account
	DeleteAccount(context.Context, *connect_go.Request[sdp_go.DeleteAccountRequest]) (*connect_go.Response[sdp_go.DeleteAccountResponse], error)
	// Lists all sources within the closen account
	ListSources(context.Context, *connect_go.Request[sdp_go.AdminListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error)
	// Creates a new source within the closen account
	CreateSource(context.Context, *connect_go.Request[sdp_go.AdminCreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error)
	// Get the details of a source within the closen account
	GetSource(context.Context, *connect_go.Request[sdp_go.AdminGetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error)
	// Update the details of a source within the closen account
	UpdateSource(context.Context, *connect_go.Request[sdp_go.AdminUpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error)
	// Deletes a source from a closen account
	DeleteSource(context.Context, *connect_go.Request[sdp_go.AdminDeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error)
	// Updates sources to keep them running in the background. This can be used
	// to add explicit action, when the built-in keepalives are not sufficient.
	KeepaliveSources(context.Context, *connect_go.Request[sdp_go.AdminKeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error)
	// Create a new NATS token for a given public NKey. The user requesting must
	// control the associated private key also in order to connect to NATS as
	// the token is not enough on its own
	CreateToken(context.Context, *connect_go.Request[sdp_go.AdminCreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	adminServiceListAccountsHandler := connect_go.NewUnaryHandler(
		AdminServiceListAccountsProcedure,
		svc.ListAccounts,
		opts...,
	)
	adminServiceCreateAccountHandler := connect_go.NewUnaryHandler(
		AdminServiceCreateAccountProcedure,
		svc.CreateAccount,
		opts...,
	)
	adminServiceGetAccountHandler := connect_go.NewUnaryHandler(
		AdminServiceGetAccountProcedure,
		svc.GetAccount,
		opts...,
	)
	adminServiceDeleteAccountHandler := connect_go.NewUnaryHandler(
		AdminServiceDeleteAccountProcedure,
		svc.DeleteAccount,
		opts...,
	)
	adminServiceListSourcesHandler := connect_go.NewUnaryHandler(
		AdminServiceListSourcesProcedure,
		svc.ListSources,
		opts...,
	)
	adminServiceCreateSourceHandler := connect_go.NewUnaryHandler(
		AdminServiceCreateSourceProcedure,
		svc.CreateSource,
		opts...,
	)
	adminServiceGetSourceHandler := connect_go.NewUnaryHandler(
		AdminServiceGetSourceProcedure,
		svc.GetSource,
		opts...,
	)
	adminServiceUpdateSourceHandler := connect_go.NewUnaryHandler(
		AdminServiceUpdateSourceProcedure,
		svc.UpdateSource,
		opts...,
	)
	adminServiceDeleteSourceHandler := connect_go.NewUnaryHandler(
		AdminServiceDeleteSourceProcedure,
		svc.DeleteSource,
		opts...,
	)
	adminServiceKeepaliveSourcesHandler := connect_go.NewUnaryHandler(
		AdminServiceKeepaliveSourcesProcedure,
		svc.KeepaliveSources,
		opts...,
	)
	adminServiceCreateTokenHandler := connect_go.NewUnaryHandler(
		AdminServiceCreateTokenProcedure,
		svc.CreateToken,
		opts...,
	)
	return "/account.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceListAccountsProcedure:
			adminServiceListAccountsHandler.ServeHTTP(w, r)
		case AdminServiceCreateAccountProcedure:
			adminServiceCreateAccountHandler.ServeHTTP(w, r)
		case AdminServiceGetAccountProcedure:
			adminServiceGetAccountHandler.ServeHTTP(w, r)
		case AdminServiceDeleteAccountProcedure:
			adminServiceDeleteAccountHandler.ServeHTTP(w, r)
		case AdminServiceListSourcesProcedure:
			adminServiceListSourcesHandler.ServeHTTP(w, r)
		case AdminServiceCreateSourceProcedure:
			adminServiceCreateSourceHandler.ServeHTTP(w, r)
		case AdminServiceGetSourceProcedure:
			adminServiceGetSourceHandler.ServeHTTP(w, r)
		case AdminServiceUpdateSourceProcedure:
			adminServiceUpdateSourceHandler.ServeHTTP(w, r)
		case AdminServiceDeleteSourceProcedure:
			adminServiceDeleteSourceHandler.ServeHTTP(w, r)
		case AdminServiceKeepaliveSourcesProcedure:
			adminServiceKeepaliveSourcesHandler.ServeHTTP(w, r)
		case AdminServiceCreateTokenProcedure:
			adminServiceCreateTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) ListAccounts(context.Context, *connect_go.Request[sdp_go.ListAccountsRequest]) (*connect_go.Response[sdp_go.ListAccountsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.ListAccounts is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateAccount(context.Context, *connect_go.Request[sdp_go.CreateAccountRequest]) (*connect_go.Response[sdp_go.CreateAccountResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.CreateAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetAccount(context.Context, *connect_go.Request[sdp_go.AdminGetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.GetAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteAccount(context.Context, *connect_go.Request[sdp_go.DeleteAccountRequest]) (*connect_go.Response[sdp_go.DeleteAccountResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.DeleteAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListSources(context.Context, *connect_go.Request[sdp_go.AdminListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.ListSources is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateSource(context.Context, *connect_go.Request[sdp_go.AdminCreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.CreateSource is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetSource(context.Context, *connect_go.Request[sdp_go.AdminGetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.GetSource is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateSource(context.Context, *connect_go.Request[sdp_go.AdminUpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.UpdateSource is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteSource(context.Context, *connect_go.Request[sdp_go.AdminDeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.DeleteSource is not implemented"))
}

func (UnimplementedAdminServiceHandler) KeepaliveSources(context.Context, *connect_go.Request[sdp_go.AdminKeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.KeepaliveSources is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateToken(context.Context, *connect_go.Request[sdp_go.AdminCreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.AdminService.CreateToken is not implemented"))
}

// ManagementServiceClient is a client for the account.ManagementService service.
type ManagementServiceClient interface {
	// Get the details of the account that this user belongs to
	GetAccount(context.Context, *connect_go.Request[sdp_go.GetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error)
	// Lists all sources within the user's account
	ListSources(context.Context, *connect_go.Request[sdp_go.ListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error)
	// Creates a new source within the user's account
	CreateSource(context.Context, *connect_go.Request[sdp_go.CreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error)
	// Get the details of a source
	GetSource(context.Context, *connect_go.Request[sdp_go.GetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error)
	// Update the details of a source
	UpdateSource(context.Context, *connect_go.Request[sdp_go.UpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error)
	// Deletes a source from a user's account
	DeleteSource(context.Context, *connect_go.Request[sdp_go.DeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error)
	// Updates sources to keep them running in the background. This can be used
	// to add explicit action, when the built-in keepalives are not sufficient.
	KeepaliveSources(context.Context, *connect_go.Request[sdp_go.KeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error)
	// Create a new NATS token for a given public NKey. The user requesting must
	// control the associated private key also in order to connect to NATS as
	// the token is not enough on its own
	CreateToken(context.Context, *connect_go.Request[sdp_go.CreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error)
}

// NewManagementServiceClient constructs a client for the account.ManagementService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManagementServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &managementServiceClient{
		getAccount: connect_go.NewClient[sdp_go.GetAccountRequest, sdp_go.GetAccountResponse](
			httpClient,
			baseURL+ManagementServiceGetAccountProcedure,
			opts...,
		),
		listSources: connect_go.NewClient[sdp_go.ListSourcesRequest, sdp_go.ListSourcesResponse](
			httpClient,
			baseURL+ManagementServiceListSourcesProcedure,
			opts...,
		),
		createSource: connect_go.NewClient[sdp_go.CreateSourceRequest, sdp_go.CreateSourceResponse](
			httpClient,
			baseURL+ManagementServiceCreateSourceProcedure,
			opts...,
		),
		getSource: connect_go.NewClient[sdp_go.GetSourceRequest, sdp_go.GetSourceResponse](
			httpClient,
			baseURL+ManagementServiceGetSourceProcedure,
			opts...,
		),
		updateSource: connect_go.NewClient[sdp_go.UpdateSourceRequest, sdp_go.UpdateSourceResponse](
			httpClient,
			baseURL+ManagementServiceUpdateSourceProcedure,
			opts...,
		),
		deleteSource: connect_go.NewClient[sdp_go.DeleteSourceRequest, sdp_go.DeleteSourceResponse](
			httpClient,
			baseURL+ManagementServiceDeleteSourceProcedure,
			opts...,
		),
		keepaliveSources: connect_go.NewClient[sdp_go.KeepaliveSourcesRequest, sdp_go.KeepaliveSourcesResponse](
			httpClient,
			baseURL+ManagementServiceKeepaliveSourcesProcedure,
			opts...,
		),
		createToken: connect_go.NewClient[sdp_go.CreateTokenRequest, sdp_go.CreateTokenResponse](
			httpClient,
			baseURL+ManagementServiceCreateTokenProcedure,
			opts...,
		),
	}
}

// managementServiceClient implements ManagementServiceClient.
type managementServiceClient struct {
	getAccount       *connect_go.Client[sdp_go.GetAccountRequest, sdp_go.GetAccountResponse]
	listSources      *connect_go.Client[sdp_go.ListSourcesRequest, sdp_go.ListSourcesResponse]
	createSource     *connect_go.Client[sdp_go.CreateSourceRequest, sdp_go.CreateSourceResponse]
	getSource        *connect_go.Client[sdp_go.GetSourceRequest, sdp_go.GetSourceResponse]
	updateSource     *connect_go.Client[sdp_go.UpdateSourceRequest, sdp_go.UpdateSourceResponse]
	deleteSource     *connect_go.Client[sdp_go.DeleteSourceRequest, sdp_go.DeleteSourceResponse]
	keepaliveSources *connect_go.Client[sdp_go.KeepaliveSourcesRequest, sdp_go.KeepaliveSourcesResponse]
	createToken      *connect_go.Client[sdp_go.CreateTokenRequest, sdp_go.CreateTokenResponse]
}

// GetAccount calls account.ManagementService.GetAccount.
func (c *managementServiceClient) GetAccount(ctx context.Context, req *connect_go.Request[sdp_go.GetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error) {
	return c.getAccount.CallUnary(ctx, req)
}

// ListSources calls account.ManagementService.ListSources.
func (c *managementServiceClient) ListSources(ctx context.Context, req *connect_go.Request[sdp_go.ListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error) {
	return c.listSources.CallUnary(ctx, req)
}

// CreateSource calls account.ManagementService.CreateSource.
func (c *managementServiceClient) CreateSource(ctx context.Context, req *connect_go.Request[sdp_go.CreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error) {
	return c.createSource.CallUnary(ctx, req)
}

// GetSource calls account.ManagementService.GetSource.
func (c *managementServiceClient) GetSource(ctx context.Context, req *connect_go.Request[sdp_go.GetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error) {
	return c.getSource.CallUnary(ctx, req)
}

// UpdateSource calls account.ManagementService.UpdateSource.
func (c *managementServiceClient) UpdateSource(ctx context.Context, req *connect_go.Request[sdp_go.UpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error) {
	return c.updateSource.CallUnary(ctx, req)
}

// DeleteSource calls account.ManagementService.DeleteSource.
func (c *managementServiceClient) DeleteSource(ctx context.Context, req *connect_go.Request[sdp_go.DeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error) {
	return c.deleteSource.CallUnary(ctx, req)
}

// KeepaliveSources calls account.ManagementService.KeepaliveSources.
func (c *managementServiceClient) KeepaliveSources(ctx context.Context, req *connect_go.Request[sdp_go.KeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error) {
	return c.keepaliveSources.CallUnary(ctx, req)
}

// CreateToken calls account.ManagementService.CreateToken.
func (c *managementServiceClient) CreateToken(ctx context.Context, req *connect_go.Request[sdp_go.CreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error) {
	return c.createToken.CallUnary(ctx, req)
}

// ManagementServiceHandler is an implementation of the account.ManagementService service.
type ManagementServiceHandler interface {
	// Get the details of the account that this user belongs to
	GetAccount(context.Context, *connect_go.Request[sdp_go.GetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error)
	// Lists all sources within the user's account
	ListSources(context.Context, *connect_go.Request[sdp_go.ListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error)
	// Creates a new source within the user's account
	CreateSource(context.Context, *connect_go.Request[sdp_go.CreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error)
	// Get the details of a source
	GetSource(context.Context, *connect_go.Request[sdp_go.GetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error)
	// Update the details of a source
	UpdateSource(context.Context, *connect_go.Request[sdp_go.UpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error)
	// Deletes a source from a user's account
	DeleteSource(context.Context, *connect_go.Request[sdp_go.DeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error)
	// Updates sources to keep them running in the background. This can be used
	// to add explicit action, when the built-in keepalives are not sufficient.
	KeepaliveSources(context.Context, *connect_go.Request[sdp_go.KeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error)
	// Create a new NATS token for a given public NKey. The user requesting must
	// control the associated private key also in order to connect to NATS as
	// the token is not enough on its own
	CreateToken(context.Context, *connect_go.Request[sdp_go.CreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error)
}

// NewManagementServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManagementServiceHandler(svc ManagementServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	managementServiceGetAccountHandler := connect_go.NewUnaryHandler(
		ManagementServiceGetAccountProcedure,
		svc.GetAccount,
		opts...,
	)
	managementServiceListSourcesHandler := connect_go.NewUnaryHandler(
		ManagementServiceListSourcesProcedure,
		svc.ListSources,
		opts...,
	)
	managementServiceCreateSourceHandler := connect_go.NewUnaryHandler(
		ManagementServiceCreateSourceProcedure,
		svc.CreateSource,
		opts...,
	)
	managementServiceGetSourceHandler := connect_go.NewUnaryHandler(
		ManagementServiceGetSourceProcedure,
		svc.GetSource,
		opts...,
	)
	managementServiceUpdateSourceHandler := connect_go.NewUnaryHandler(
		ManagementServiceUpdateSourceProcedure,
		svc.UpdateSource,
		opts...,
	)
	managementServiceDeleteSourceHandler := connect_go.NewUnaryHandler(
		ManagementServiceDeleteSourceProcedure,
		svc.DeleteSource,
		opts...,
	)
	managementServiceKeepaliveSourcesHandler := connect_go.NewUnaryHandler(
		ManagementServiceKeepaliveSourcesProcedure,
		svc.KeepaliveSources,
		opts...,
	)
	managementServiceCreateTokenHandler := connect_go.NewUnaryHandler(
		ManagementServiceCreateTokenProcedure,
		svc.CreateToken,
		opts...,
	)
	return "/account.ManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManagementServiceGetAccountProcedure:
			managementServiceGetAccountHandler.ServeHTTP(w, r)
		case ManagementServiceListSourcesProcedure:
			managementServiceListSourcesHandler.ServeHTTP(w, r)
		case ManagementServiceCreateSourceProcedure:
			managementServiceCreateSourceHandler.ServeHTTP(w, r)
		case ManagementServiceGetSourceProcedure:
			managementServiceGetSourceHandler.ServeHTTP(w, r)
		case ManagementServiceUpdateSourceProcedure:
			managementServiceUpdateSourceHandler.ServeHTTP(w, r)
		case ManagementServiceDeleteSourceProcedure:
			managementServiceDeleteSourceHandler.ServeHTTP(w, r)
		case ManagementServiceKeepaliveSourcesProcedure:
			managementServiceKeepaliveSourcesHandler.ServeHTTP(w, r)
		case ManagementServiceCreateTokenProcedure:
			managementServiceCreateTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedManagementServiceHandler struct{}

func (UnimplementedManagementServiceHandler) GetAccount(context.Context, *connect_go.Request[sdp_go.GetAccountRequest]) (*connect_go.Response[sdp_go.GetAccountResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.GetAccount is not implemented"))
}

func (UnimplementedManagementServiceHandler) ListSources(context.Context, *connect_go.Request[sdp_go.ListSourcesRequest]) (*connect_go.Response[sdp_go.ListSourcesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.ListSources is not implemented"))
}

func (UnimplementedManagementServiceHandler) CreateSource(context.Context, *connect_go.Request[sdp_go.CreateSourceRequest]) (*connect_go.Response[sdp_go.CreateSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.CreateSource is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetSource(context.Context, *connect_go.Request[sdp_go.GetSourceRequest]) (*connect_go.Response[sdp_go.GetSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.GetSource is not implemented"))
}

func (UnimplementedManagementServiceHandler) UpdateSource(context.Context, *connect_go.Request[sdp_go.UpdateSourceRequest]) (*connect_go.Response[sdp_go.UpdateSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.UpdateSource is not implemented"))
}

func (UnimplementedManagementServiceHandler) DeleteSource(context.Context, *connect_go.Request[sdp_go.DeleteSourceRequest]) (*connect_go.Response[sdp_go.DeleteSourceResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.DeleteSource is not implemented"))
}

func (UnimplementedManagementServiceHandler) KeepaliveSources(context.Context, *connect_go.Request[sdp_go.KeepaliveSourcesRequest]) (*connect_go.Response[sdp_go.KeepaliveSourcesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.KeepaliveSources is not implemented"))
}

func (UnimplementedManagementServiceHandler) CreateToken(context.Context, *connect_go.Request[sdp_go.CreateTokenRequest]) (*connect_go.Response[sdp_go.CreateTokenResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("account.ManagementService.CreateToken is not implemented"))
}
