// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: sdp/v2/main.proto

package sdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The primary frame that gets sent over SDP connections. This allows for a
// variety of commands to be sent and received with easy multiplexing and
// re-assembling of responses b using the `uuid` field to link requests and
// responses.
type SdpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID of the request
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The deadline for how long the sender is willing to wait for responses
	Deadline *durationpb.Duration `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *SdpRequest) Reset() {
	*x = SdpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdp_v2_main_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpRequest) ProtoMessage() {}

func (x *SdpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdp_v2_main_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpRequest.ProtoReflect.Descriptor instead.
func (*SdpRequest) Descriptor() ([]byte, []int) {
	return file_sdp_v2_main_proto_rawDescGZIP(), []int{0}
}

func (x *SdpRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SdpRequest) GetDeadline() *durationpb.Duration {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type SdpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID of the request
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *SdpResponse) Reset() {
	*x = SdpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdp_v2_main_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdpResponse) ProtoMessage() {}

func (x *SdpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdp_v2_main_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdpResponse.ProtoReflect.Descriptor instead.
func (*SdpResponse) Descriptor() ([]byte, []int) {
	return file_sdp_v2_main_proto_rawDescGZIP(), []int{1}
}

func (x *SdpResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_sdp_v2_main_proto protoreflect.FileDescriptor

var file_sdp_v2_main_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x64, 0x70, 0x2f, 0x76, 0x32, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x64, 0x70, 0x2e, 0x76, 0x32, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x0a, 0x53,
	0x64, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x35, 0x0a,
	0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x64, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x64, 0x74, 0x65,
	0x63, 0x68, 0x2f, 0x73, 0x64, 0x70, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x64, 0x70, 0x2f, 0x76, 0x32,
	0x3b, 0x73, 0x64, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdp_v2_main_proto_rawDescOnce sync.Once
	file_sdp_v2_main_proto_rawDescData = file_sdp_v2_main_proto_rawDesc
)

func file_sdp_v2_main_proto_rawDescGZIP() []byte {
	file_sdp_v2_main_proto_rawDescOnce.Do(func() {
		file_sdp_v2_main_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdp_v2_main_proto_rawDescData)
	})
	return file_sdp_v2_main_proto_rawDescData
}

var file_sdp_v2_main_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdp_v2_main_proto_goTypes = []interface{}{
	(*SdpRequest)(nil),          // 0: sdp.v2.SdpRequest
	(*SdpResponse)(nil),         // 1: sdp.v2.SdpResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_sdp_v2_main_proto_depIdxs = []int32{
	2, // 0: sdp.v2.SdpRequest.deadline:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdp_v2_main_proto_init() }
func file_sdp_v2_main_proto_init() {
	if File_sdp_v2_main_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdp_v2_main_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdp_v2_main_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdp_v2_main_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdp_v2_main_proto_goTypes,
		DependencyIndexes: file_sdp_v2_main_proto_depIdxs,
		MessageInfos:      file_sdp_v2_main_proto_msgTypes,
	}.Build()
	File_sdp_v2_main_proto = out.File
	file_sdp_v2_main_proto_rawDesc = nil
	file_sdp_v2_main_proto_goTypes = nil
	file_sdp_v2_main_proto_depIdxs = nil
}
